### ISSUE TITLE
remove travis yaml 

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#20]
currently travis does not seem t be set up.

Let's fix that

**Comment by pixelass** [comment]
I didn't notice that circle-ci is running.

I don't think we need two ci tools so IMHO we can just remove travis.yml (it runs invalid scripts anyways /pre lerna)

**Comment by MattMcFarland** [comment]
agreed,

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
