### ISSUE TITLE
Automatic manual page detection

### ISSUE THREAD

**Issue by rgsilva** [esdoc2/esdoc2-plugins#3]
Hi!

Any chance I can create a manual based on a path only? For example:

```
        "manual": {
          "index": "./manual/index.md",
          "files": [
            "./manual/foobar/*.md"
          ]
        }
```

I took a look at the documentation but couldn't find any easy way of doing that. I thought about making a script that would take a look at the manual folder and modify the final esdoc.json, but that would be kinda annoying. I also considered using the ```ESDoc``` class itself for that, but that would require loading ESDoc in a JS file, which has been a _pita_ on my setup.

The way I see, there are two solutions for this: either use the class by itself, which is probably the best one, or modify the `esdoc2-integrate-manual-plugin` to use `glob` to load the paths (and therefore supporting wildcards).

Any ideas? Thanks!

**Comment by MattMcFarland** [comment]
Definitely should update it to use `glob` 👍

**Comment by rgsilva** [comment]
Closing as it has been merged already. :smile:
