### ISSUE TITLE
custom theme plugin

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#9]
Hi. I just found this repo and wanted to say hi and thank you. I also have issues with esdoc maintainers not responding to severe security issues being reported and features being rejected or not even respected.

I love esdoc in general and want to emphasise that the original creator did an amazing job so far. I am pretty sure there are reasons for the sudden lack of response. I do think there are a lot of open issues though and would love to help get some of them done, especially anything having to do with vulnerabilities and helping to detect these better.

IMHO a documentation is a lot about appearance, so I created a custom theme which works perfectly with the plugin mechanism of esdoc.

Maybe you are interested in this theme. Feel free to fork it or even strip it to its bare bones and use it as a default theme. I think if I get access to the publish-html-plugin I can fix a lot of issues I am currently handling via javascript on the client.

So before I start creating my own plugins for esdoc I wanted to offer some help.

Here's the theme I made. 
It has a neat set of options which make it very special.

**Repo:** https://github.com/sinnerschrader/esdoc-custom-theme
**Demo:** https://sinnerschrader.github.io/esdoc-custom-theme/

Cheers Pixelass

**Comment by MattMcFarland** [comment]
I like this a lot.  I'd love to have you as a member of esdoc2, will send invite.

**Comment by pixelass** [comment]
Thx for the invite.
I will add a new plugin for the theme. 

**This issue will be closed automatically by the pull request.**

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
